### ISSUE TITLE
(react-native-app): WalletConnect doesn't work on Android 11+

### ISSUE THREAD

**Issue by libengd** [celo-org/celo-composer#120]
When trying to connect to wallet using WalletConnect on Android 11+ it redirects you to `https://walletconnect.com/wallets` instead. Its because starting from Android 11 you must specify query intents in `AndroidManifest.xml` for `canOpenUrl` to return true.

https://reactnative.dev/docs/linking#canopenurl

![image](https://user-images.githubusercontent.com/102393474/185280449-064178b4-c874-4eb3-81d6-374135d2cded.png)

https://github.com/WalletConnect/walletconnect-monorepo/issues/966

Possible solution: use config-plugin with Expo EAS to edit `AndroidManifest.xml`

**Comment by somewheregreeny** [comment]
I'm sorry for checking late. It was very helpful. Thank you.

**Comment by therealharpaljadeja** [comment]
the react-native-app (expo version) has instructions in the readme to resolve this issue.
