### ISSUE TITLE
Wrong @types/react version when running 

### ISSUE THREAD

**Issue by yuliyu123** [celo-org/celo-composer#140]
when run `yarn dev`, such error happened:
```
gitpod /workspace/celo_composer_learn/packages/react-app (main) $ yarn dev
yarn run v1.22.19
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
It looks like you're trying to use TypeScript but do not have the required package(s) installed.

Please install @types/react by running:

        yarn add --dev @types/react

If you are not trying to use TypeScript, please remove the tsconfig.json file from your package root (and any TypeScript files in your pages directory).
```
 It's because the @types/react inside package.json is not compatible, need to downgrade the pakcage.

Another error:
```
react-celo] The `network` prop on CeloProvider has been deprecated, use `defaultNetwork`
```

If needed, I'm glad to fix such two issues.

**Comment by alymurtazamemon** [comment]
Facing same issue

**Comment by alymurtazamemon** [comment]
Solved the first issue by downgrading the @types/react. But still facing a second issue.

**Comment by viral-sangani** [comment]
@alymurtazamemon You can change the `network` to `defaultNetwork` and the value to `Alfajoes` (string). We will update it in the repo too.

**Comment by nestorbonilla** [comment]
It seems the issue has been solved. Closing it.
