### ISSUE TITLE
Import of deployedContract is wrong in side react-native start up park

### ISSUE THREAD

**Issue by otim22** [celo-org/celo-composer#151]
### Which Framework?

React Native

### What happened?

On the index file in the navigation folder line 26 importing deployedContracts import link is wrong
And missing light and dark color styles in the Colors.ts constants
### Steps to reproduce

1. After cloning and installing celo-composer
2. cd to react-native and start the app

**Comment by viral-sangani** [comment]
@otim22 Looking into it.

**Comment by therealharpaljadeja** [comment]
@viral-sangani any updates here?
