### ISSUE TITLE
Update README documentation

### ISSUE THREAD

**Issue by otim22** [celo-org/celo-composer#152]
### Tell us about your idea

I have identified less documentation on the celo-composer repo
And I want to make a pull request on the celo-composer to add more clarity
How can I achieve this?? 
I have already cloned the repo 
And made the necessary changes but I am unable to push up the changes

**Comment by viral-sangani** [comment]
@otim22 You will have to fork the repo, make the updates, and then raise a PR to official repo.

**Comment by nestorbonilla** [comment]
Hi @otim22, please let us know if you've any other questions.
Closing issue for not having activity in several months.
