### ISSUE TITLE
[Bug]: Project Name can't have space

### ISSUE THREAD

**Issue by therealharpaljadeja** [celo-org/celo-composer#158]
### Which Framework?

React, Hardhat

### What happened?

If your project name has a space then we get the following error.

![image](https://user-images.githubusercontent.com/38040789/202262640-7d30cad0-5bbe-4d22-a9be-2944fdc185d8.png)

### Steps to reproduce

When executing the create command give a space to the project name.

**Comment by therealharpaljadeja** [comment]
@viral-sangani any updates on this?

**Comment by daryazata** [comment]
@therealharpaljadeja is it still an issue? i can try work on this

**Comment by daryazata** [comment]
![Bildschirmfoto 2024-07-09 um 14 05 39](https://github.com/celo-org/celo-composer/assets/44365122/830121c3-484a-46a7-86ff-33be2f25b390)
getting some warnings when installing ..
