### ISSUE TITLE
Fix grammatical mistake and error in README.md file,

### ISSUE THREAD

**Issue by J0shcodes** [celo-org/celo-composer#187]
### Which Framework?

React

### What happened?

The word "Installation" is spelt as "Intallation" in the README.md file.

### Steps to reproduce

Read the README.md file.

### Anything else?

The file can be found at https://github.com/celo-org/celo-composer/blob/main/packages/react-app/README.md

**Comment by nestorbonilla** [comment]
Thanks, @J0shcodes! Fixed on PR #188.
