### ISSUE TITLE
[Feature]: options to select the language for development

### ISSUE THREAD

**Issue by jim4067** [celo-org/celo-composer#192]
### Tell us about your idea

When you generate a new project with composer, it initializes the hardhat(`tests and config`) package with JavaScript and the frontend package with TypeScript. 

I would love the option to be able to generate a project with the language I want to use, e.g generate the whole project to use TypeScript or JavaScript or mix and match using JS on the front end and TS on the contracts(`tests`).

**Comment by therealharpaljadeja** [comment]
You willing to take this up?
