### ISSUE TITLE
No Oracle contract to test using hardhat[Bug]: 

### ISSUE THREAD

**Issue by EmanHerawy** [celo-org/celo-composer#219]
### Which Framework?

React, Hardhat

### What happened?

Hey guys,
I was working on the composer for a workshop I'm providing and notice that you have t[est for oracle contract ](https://github.com/celo-org/celo-composer/blob/1862ccb670770f95ea0e45e7751acc0546b61391/packages/hardhat/test/oracle-test.js#L9C48-L9C48) while the contracts directory doesn't have this contract. I had to remove it manually to make ` yarn run hardhat:test` command works.  

### Steps to reproduce

1.  use composer to kick start your project 
2.  select hardhat framework
3.  run `yarn install` and add your `.env` file 
4.  run `yarn run hardhat:test`

**Comment by therealharpaljadeja** [comment]
Resolved.
