### ISSUE TITLE
[Feature]: Replace `react-celo` + `contractKit` with `rainbowkit` + `viem`

### ISSUE THREAD

**Issue by 0xarthurxyz** [celo-org/celo-composer#220]
### Tell us about your idea

Since we are aiming to promote the use popular web3 libraries on Celo, we should consider making the Celo Composer defaults:

- [x] rainbowkit (instead of react-celo, if that's not already the case), and 
- [x] viem (instead of contractkit)

**Comment by therealharpaljadeja** [comment]
`react-app` now uses `@celo/rainbowkit-celo`, `viem` and `wagmi`


https://github.com/celo-org/celo-composer/blob/60e0fe76b6b896441ca629c6620626197752cc88/packages/react-app/package.json#L11-L22
