### ISSUE TITLE
[Feature]: Where is the Flutter one?

### ISSUE THREAD

**Issue by mortzaCFT** [celo-org/celo-composer#298]
### Tell us about your idea

Hello and thanks for making such great lib, but unfortunately I seen your lib doesn't have ability to use with Flutter/Dart too.
Refer to this repo :

https://github.com/jonyoung123/Decentralized-Chat-DApp-with-Celo-and-flutter

That created by John Igwe Eke, and also in this tuturial of him, that actually have a doc on celo academy :

https://celo.academy/t/integrating-decentralized-chat-app-using-celo-composer-and-flutter/1904

This feature was in this package , at lasted for one year ago , and i like to use your package instead of others to deploy my chat app using flutter as front end, but it seems this feature has been deleted.

Can anyone tell me the reason and maybe the roadmap?

With regards.

**Comment by GigaHierz** [comment]
Hi @mortzaCFT , 

thank you for your interest in the Celo Composer. the Flutter version was removed as it was not maintained and the Celo Composer has been updated.

We are working on providing a new Flutter version of the Celo Composer and we have created a ticket for it with #302
