### ISSUE TITLE
[Feature]: Add guide on how to deploy on Vercel through the Vercel CLI

### ISSUE THREAD

**Issue by GigaHierz** [celo-org/celo-composer#300]
### Tell us about your idea

Currently, for people unfamiliar with Vercel, it takes some time to deploy their project. 
Providing a simple guide on how to deploy it with Vercel, using the Vercel CLI would be useful.

- [ ] add a Guide to deploy the project with Vercel CLI
- [ ] add that guide to the Quickstart in the docs as well

**Comment by viral-sangani** [comment]
Completed - #311

**Comment by GigaHierz** [comment]
Closed by #311
