### ISSUE TITLE
Superfluid integration

### ISSUE THREAD

**Issue by joenyzio** [celo-org/celo-composer#60]
Make [Superfluid](https://app.superfluid.finance/) available within composer with basic directions on usage.

**Comment by lopeselio** [comment]
I have been working on ways to make cUSD streams using ERC-1620 token standard used by Sablier

**Comment by viral-sangani** [comment]
Great @lopeselio 🎉 
Let us know if we can be of any help.

**Comment by therealharpaljadeja** [comment]
@lopeselio any update on this?
